on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.0
      with:
        ftp-server: ftp://v0.ftp.upyun.com/
        ftp-username: qq1012/guluo
        ftp-password: DwmyMbfIOqcHLZpZvAP3mAGkwkU7e2I5
